name: Daily Programming Tip

on:
  schedule:
    # Run at 9:00 AM UTC every day
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  post-programming-tip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests groq
        
    - name: Generate and Post Programming Tip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        REPO_NAME: ${{ github.repository_owner }}/.discussions
        DISCUSSION_CATEGORY_ID: ${{ vars.DISCUSSION_CATEGORY_ID }}
      run: |
        python .github/scripts/generate_tip.py
